# numpy means numerical python


linspace linearly space
0 to 1 is uniform distribution
1.diff btw list and tuple
2.negative to positive value normal distribution
3.standard normal distribution
4.compare uniform ,normal,and standard distribution 


In [2]:
import numpy as np
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [3]:
np.arange(1,32,5) #shift+tab->help box

array([ 1,  6, 11, 16, 21, 26, 31])

In [5]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [8]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [9]:
list_of_lists=[[1,2,3],[4,5,6]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [11]:
np.random.rand(3,5)

array([[2.52925311e-01, 5.79073859e-01, 7.09426882e-01, 9.45106814e-01,
        2.38836062e-01],
       [9.88618779e-01, 6.60684885e-01, 7.96400160e-01, 7.84915360e-01,
        2.52796285e-01],
       [1.61258684e-01, 8.93196960e-01, 9.58180163e-04, 3.48214452e-01,
        7.01267299e-02]])

In [13]:
ar=np.random.randn(2,4)
ar


array([[-0.08714189,  0.68380293, -0.30600396, -0.72162172],
       [-2.42627577, -1.99798646,  1.1023781 , -0.59773716]])

In [14]:
np.random.randint(20,56,100)

array([21, 46, 28, 48, 32, 43, 53, 21, 38, 47, 45, 36, 52, 47, 22, 52, 28,
       46, 26, 46, 50, 26, 47, 25, 48, 54, 23, 31, 28, 33, 35, 47, 21, 41,
       35, 36, 25, 30, 29, 31, 22, 55, 22, 22, 35, 43, 48, 21, 32, 27, 29,
       52, 21, 40, 49, 42, 42, 41, 31, 35, 47, 40, 41, 35, 55, 35, 25, 20,
       42, 37, 37, 26, 45, 49, 48, 46, 23, 49, 55, 34, 22, 50, 27, 51, 23,
       48, 32, 36, 23, 42, 29, 40, 38, 34, 46, 35, 28, 52, 43, 55])

In [16]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
rand_array=np.random.randint(0,10,50)
rand_array

array([3, 2, 6, 5, 2, 1, 5, 1, 0, 1, 0, 4, 6, 9, 5, 0, 5, 1, 6, 7, 4, 6,
       6, 3, 5, 1, 5, 8, 4, 0, 9, 3, 5, 5, 9, 6, 6, 2, 4, 4, 1, 0, 2, 8,
       9, 8, 3, 1, 7, 1])

In [19]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [20]:
rand_array.max()

9

In [21]:
rand_array.argmax()

13

In [23]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
a=np.random.rand(2,3)
a

array([[0.98280337, 0.33139726, 0.22792394],
       [0.32507798, 0.87783481, 0.14960749]])

In [26]:
a.T

array([[0.98280337, 0.32507798],
       [0.33139726, 0.87783481],
       [0.22792394, 0.14960749]])

In [27]:
sample_array=np.arange(10,21)
sample_array


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
sample_array[0]

10

In [29]:
sample_array[2:5]

array([12, 13, 14])

In [30]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [31]:
sample_array=np.arange(10,21)
sample_array


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [33]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [34]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# pandas dataframe and indexing

In [1]:
import pandas as pd
import numpy as np

In [4]:
fruits1=pd.Series([1,2,3,4],index=["apple","banana","mango","guava"])
fruits1


apple     1
banana    2
mango     3
guava     4
dtype: int64

In [6]:
fruits1["mango"]

3

In [9]:
fruits2=pd.Series([11,2,3,4],index=["watermelon","muskmelon","orange","strawberry"])
fruits2


watermelon    11
muskmelon      2
orange         3
strawberry     4
dtype: int64

In [12]:
df2={"ID":["101","102","103","107","176"],"Name":["mansi","nigar","nikita","anjali","aditi"],"Profit":[23,56,45,12,78]}
df=pd.DataFrame(df2)
df

ID    Name  Profit
0  101   mansi      23
1  102   nigar      56
2  103  nikita      45
3  107  anjali      12
4  176   aditi      78

In [13]:
df["ID"]


0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [16]:
df[["ID","Name"]]

ID    Name
0  101   mansi
1  102   nigar
2  103  nikita
3  107  anjali
4  176   aditi

In [17]:
df=df.drop("ID",axis=1)
df

Name  Profit
0   mansi      23
1   nigar      56
2  nikita      45
3  anjali      12
4   aditi      78

In [18]:
df.drop(3)

Name  Profit
0   mansi      23
1   nigar      56
2  nikita      45
4   aditi      78

# how to import dataset using pandas

In [19]:
import numpy as np
import pandas as pd

In [23]:
df=pd.read_csv("titanic-training-data.csv")

In [24]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [25]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [26]:
df.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [27]:
df.sample(10)

PassengerId  Survived  Pclass  \
636          637         0       3   
377          378         0       1   
828          829         1       3   
695          696         0       2   
82            83         1       3   
786          787         1       3   
111          112         0       3   
589          590         0       3   
25            26         1       3   
821          822         1       3   

                                                  Name     Sex   Age  SibSp  \
636                         Leinonen, Mr. Antti Gustaf    male  32.0      0   
377                          Widener, Mr. Harry Elkins    male  27.0      0   
828                       McCormack, Mr. Thomas Joseph    male   NaN      0   
695                         Chapman, Mr. Charles Henry    male  52.0      0   
82                      McDermott, Miss. Brigdet Delia  female   NaN      0   
786                          Sjoblom, Miss. Anna Sofia  female  18.0      0   
111                               Zabour, Miss. Hileni  female  14.5      1   
589                                Murdlin, Mr. Joseph    male   NaN      0   
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
821                                  Lulic, Mr. Nikola    male  27.0      0   

     Parch             Ticket      Fare Cabin Embarked  
636      0  STON/O 2. 3101292    7.9250   NaN        S  
377      2             113503  211.5000   C82        C  
828      0             367228    7.7500   NaN        Q  
695      0             248731   13.5000   NaN        S  
82       0             330932    7.7875   NaN        Q  
786      0            3101265    7.4958   NaN        S  
111      0               2665   14.4542   NaN        C  
589      0         A./5. 3235    8.0500   NaN        S  
25       5             347077   31.3875   NaN        S  
821      0             315098    8.6625   NaN        S

In [29]:
df.shape

(891, 12)

In [30]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [31]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [33]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [34]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [35]:
df.describe(include="all")

PassengerId    Survived      Pclass                     Name   Sex  \
count    891.000000  891.000000  891.000000                      891   891   
unique          NaN         NaN         NaN                      891     2   
top             NaN         NaN         NaN  Braund, Mr. Owen Harris  male   
freq            NaN         NaN         NaN                        1   577   
mean     446.000000    0.383838    2.308642                      NaN   NaN   
std      257.353842    0.486592    0.836071                      NaN   NaN   
min        1.000000    0.000000    1.000000                      NaN   NaN   
25%      223.500000    0.000000    2.000000                      NaN   NaN   
50%      446.000000    0.000000    3.000000                      NaN   NaN   
75%      668.500000    1.000000    3.000000                      NaN   NaN   
max      891.000000    1.000000    3.000000                      NaN   NaN   

               Age       SibSp       Parch  Ticket        Fare    Cabin  \
count   714.000000  891.000000  891.000000     891  891.000000      204   
unique         NaN         NaN         NaN     681         NaN      147   
top            NaN         NaN         NaN  347082         NaN  B96 B98   
freq           NaN         NaN         NaN       7         NaN        4   
mean     29.699118    0.523008    0.381594     NaN   32.204208      NaN   
std      14.526497    1.102743    0.806057     NaN   49.693429      NaN   
min       0.420000    0.000000    0.000000     NaN    0.000000      NaN   
25%      20.125000    0.000000    0.000000     NaN    7.910400      NaN   
50%      28.000000    0.000000    0.000000     NaN   14.454200      NaN   
75%      38.000000    1.000000    0.000000     NaN   31.000000      NaN   
max      80.000000    8.000000    6.000000     NaN  512.329200      NaN   

       Embarked  
count       889  
unique        3  
top           S  
freq        644  
mean        NaN  
std         NaN  
min         NaN  
25%         NaN  
50%         NaN  
75%         NaN  
max         NaN

In [36]:
import pandas as pd
import numpy as np

In [37]:
df=pd.read_csv("loan_prediction.csv")

In [38]:
df.shape

(614, 13)

In [39]:
df.head(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   
6  LP001013   Male     Yes          0  Not Graduate            No   
7  LP001014   Male     Yes         3+      Graduate            No   
8  LP001018   Male     Yes          2      Graduate            No   
9  LP001020   Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [40]:
df.tail(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not Graduate            No   
608  LP002974    Male     Yes          0      Graduate            No   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
604            12000                0.0       496.0             360.0   
605             2400             3800.0         NaN             180.0   
606             3400             2500.0       173.0             360.0   
607             3987             1411.0       157.0             360.0   
608             3232             1950.0       108.0             360.0   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
604             1.0     Semiurban           Y  
605             1.0         Urban           N  
606             1.0     Semiurban           Y  
607             1.0         Rural           Y  
608             1.0         Rural           Y  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [42]:
df.describe()     #mathematics

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [43]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [44]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [45]:
df.sample(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
38   LP001114    Male      No          0      Graduate            No   
580  LP002892    Male     Yes          2      Graduate            No   
240  LP001798    Male     Yes          2      Graduate            No   
10   LP001024    Male     Yes          2      Graduate            No   
260  LP001865    Male     Yes          1      Graduate            No   
160  LP001560    Male     Yes          0  Not Graduate            No   
368  LP002190    Male     Yes          1      Graduate            No   
512  LP002643    Male     Yes          2      Graduate            No   
198  LP001671  Female     Yes          0      Graduate            No   
497  LP002588    Male     Yes          0      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
38              4166             7210.0       184.0             360.0   
580             6540                0.0       205.0             360.0   
240             5819             5000.0       120.0             360.0   
10              3200              700.0        70.0             360.0   
260             6083             4250.0       330.0             360.0   
160             1863             1041.0        98.0             360.0   
368             6325                0.0       175.0             360.0   
512             3283             2035.0       148.0             360.0   
198             3416             2816.0       113.0             360.0   
497             4625             2857.0       111.0              12.0   

     Credit_History Property_Area Loan_Status  
38              1.0         Urban           Y  
580             1.0     Semiurban           Y  
240             1.0         Rural           Y  
10              1.0         Urban           Y  
260             NaN         Urban           Y  
160             1.0     Semiurban           Y  
368             1.0     Semiurban           Y  
512             1.0         Urban           Y  
198             NaN     Semiurban           Y  
497             NaN         Urban           Y

In [46]:
df.describe(include="all")

Loan_ID Gender Married Dependents Education Self_Employed  \
count        614    601     611        599       614           582   
unique       614      2       2          4         2             2   
top     LP001002   Male     Yes          0  Graduate            No   
freq           1    489     398        345       480           500   
mean         NaN    NaN     NaN        NaN       NaN           NaN   
std          NaN    NaN     NaN        NaN       NaN           NaN   
min          NaN    NaN     NaN        NaN       NaN           NaN   
25%          NaN    NaN     NaN        NaN       NaN           NaN   
50%          NaN    NaN     NaN        NaN       NaN           NaN   
75%          NaN    NaN     NaN        NaN       NaN           NaN   
max          NaN    NaN     NaN        NaN       NaN           NaN   

        ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count        614.000000         614.000000  592.000000         600.00000   
unique              NaN                NaN         NaN               NaN   
top                 NaN                NaN         NaN               NaN   
freq                NaN                NaN         NaN               NaN   
mean        5403.459283        1621.245798  146.412162         342.00000   
std         6109.041673        2926.248369   85.587325          65.12041   
min          150.000000           0.000000    9.000000          12.00000   
25%         2877.500000           0.000000  100.000000         360.00000   
50%         3812.500000        1188.500000  128.000000         360.00000   
75%         5795.000000        2297.250000  168.000000         360.00000   
max        81000.000000       41667.000000  700.000000         480.00000   

        Credit_History Property_Area Loan_Status  
count       564.000000           614         614  
unique             NaN             3           2  
top                NaN     Semiurban           Y  
freq               NaN           233         422  
mean          0.842199           NaN         NaN  
std           0.364878           NaN         NaN  
min           0.000000           NaN         NaN  
25%           1.000000           NaN         NaN  
50%           1.000000           NaN         NaN  
75%           1.000000           NaN         NaN  
max           1.000000           NaN         NaN